# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59feee966880e04a81f0f4a968b81cccac52dc3acb3511aa940337026c0ec1c7e47c53223b14dd8f674de33ab1aa424db935775bb3edb44f86c1d7db64305d0e

test:
  secret_key_base: 217ad85aa7a03c9d75e038f002b5f734d97ec0ab81cdba30efc4024fdf41e7c86bb872aaff8bcb83ced241449a1bac42c2dc5645147830506764cab38972943f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
